# Generated by Django 5.0.2 on 2024-03-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='content',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='published_data',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
