# Generated by Django 5.0.2 on 2024-03-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_title_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(to='blog.category', verbose_name='Пости'),
        ),
    ]
