# Generated by Django 5.0.2 on 2024-03-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_tag_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Пошта')),
            ],
            options={
                'verbose_name': 'Пошта',
            },
        ),
        migrations.AlterField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(to='blog.post', verbose_name='Пости'),
        ),
    ]
