# Generated by Django 5.0.2 on 2024-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_subscribe_alter_tag_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Пошта', 'verbose_name_plural': 'Пошта'},
        ),
        migrations.AddField(
            model_name='subscribe',
            name='user',
            field=models.CharField(default='', max_length=30, verbose_name='Користувач'),
        ),
    ]
