# Generated by Django 5.0.2 on 2024-03-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_subscribe_options_subscribe_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
    ]
