# Generated by Django 5.0.2 on 2024-03-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text_length',
        ),
    ]
