# Generated by Django 5.0.3 on 2024-04-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_profile_wer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile_wer',
            options={'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name="Ім'я"),
        ),
    ]
